'use strict';
const $=id=>document.getElementById(id);
let ready=false,busy=false,state='crate',hotkey='Space',chimes=true,enrolled=true;
let senses={camera:false,mic:false,open_mic:false},reply=null,level=0,ptt=false,polling=false;
let visibleTab='tab-chat',records=[],lastTelemetry=0,startingMic=false;
window.desktopNotice=function(text){const n=document.createElement('div');n.className='notice';n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),6500);};
async function call(command,payload={}){try{const r=await window.pywebview.api.request(command,payload);if(!r.ok)window.desktopNotice(r.error||'Operation unavailable.');return r;}catch(e){window.desktopNotice('The desktop connection is unavailable. Restart JARVIS.');return {ok:false};}}
function show(id,on=true){$(id).style.display=on?'':'none';}
function text(id,value){$(id).textContent=value;}
function message(value,type='exo'){const row=document.createElement('div');row.className='message msg-'+type;const bubble=document.createElement('div');bubble.className='msg-bubble';bubble.textContent=value;row.append(bubble);$('chat-messages').append(row);$('chat-messages').scrollTop=$('chat-messages').scrollHeight;return bubble;}
function senseDisplay(){ $('toggle-camera').checked=senses.camera;$('toggle-voice').checked=senses.mic;text('btn-toggle-voice-mode',senses.open_mic?'Open-Mic · ON':'Push-to-Talk'); }
function setState(next){state=next;text('eye-status',next.toUpperCase());show('btn-trigger-wake',next==='sleeping');show('btn-trigger-sleep',next!=='sleeping');text('btn-quick-sleep',next==='sleeping'?'☀ Wake JARVIS':'☾ Put to Sleep');show('voice-strip',next==='listening'||next==='speaking');text('voice-strip-label',next==='speaking'?'SPEAKING':'LISTENING');$('btn-ptt').classList.toggle('recording',next==='listening');}
function sound(kind){if(!chimes)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='wake'?220:110,c.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='wake'?440:55,c.currentTime+1.2);g.gain.setValueAtTime(0.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.055,c.currentTime+.12);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+1.5);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+1.6);o.onended=()=>c.close();}catch(e){}}
function progress(e,complete=false){show('sleep-results');text('sleep-val-scanned',e.scanned);text('sleep-val-proposed',e.candidates);text('sleep-val-applied',e.dropped);text('sleep-val-tsc',complete?(e.verified?'PASS':'FAILED'):'Checking…');text('proposals-feed',complete?'Consolidation finished. Candidates are queued for review; no core changes were applied.':'Evaluating significant events…');}
function handle(e){switch(e.kind){case 'reply_start':reply=message('');break;case 'reply_chunk':if(!reply)reply=message('');reply.textContent+=e.text;$('chat-messages').scrollTop=$('chat-messages').scrollHeight;break;case 'reply_end':reply=null;break;case 'transcript':message(e.text,'user');break;case 'tool':message(e.name+'\n'+e.text,'tool');break;case 'denial':{const n=document.createElement('div');n.textContent=new Date().toLocaleTimeString()+' · '+e.text;const f=$('quarantine-feed');if(f.querySelector('.log-empty'))f.replaceChildren();f.prepend(n);message(e.text,'system');break;}case 'error':window.desktopNotice(e.text);break;case 'sleep_progress':progress(e);break;case 'sleep_complete':progress(e,true);setState('sleeping');sound('sleep');break;case 'wake':setState('idle');sound('wake');break;}}
async function poll(){if(polling||!ready)return;polling=true;try{const r=await call('poll');if(r.ok){busy=r.busy;level=r.level;senses=r.senses;setState(r.state);senseDisplay();r.events.forEach(handle);$('btn-send-text').disabled=busy||state==='sleeping';if(!busy&&state==='idle'&&senses.open_mic&&senses.mic&&!startingMic){startingMic=true;await call('record_start');startingMic=false;}}if(Date.now()-lastTelemetry>2000){lastTelemetry=Date.now();await telemetry();}}finally{polling=false;}}
async function telemetry(){const r=await call('telemetry');if(!r.ok)return;const g=r.telemetry.gpu,m=r.telemetry.ram,c=r.clock;const used=g.vram_used_mb??g.used_mb??0,total=g.vram_total_mb??g.total_mb??0;const pct=total?Math.round(used/total*100):0;text('gauge-gpu-name',g.name||'GPU unavailable');text('gauge-vram-text',total?`${used} MB / ${total} MB`:'Unavailable');text('mini-vram',total?`${used} / ${total} MB`:'Unavailable');for(const id of ['gauge-vram-fill','mini-vram-fill'])$(id).style.width=pct+'%';text('gauge-vram-pct',pct+'%');text('gauge-gpu-util',(g.utilization_pct??g.util_pct??0)+'%');text('gauge-ram-text',`${m.used_gb} GB / ${m.total_gb} GB`);text('gauge-ram-avail',m.avail_gb+' GB');text('gauge-ram-pct',m.load_pct+'%');$('gauge-ram-fill').style.width=m.load_pct+'%';const seconds=r.telemetry.uptime_seconds??c.uptime_seconds??0;const uptime=new Date(seconds*1000).toISOString().slice(11,19);text('gauge-uptime-text',uptime);text('mini-uptime',uptime);text('gauge-clock-time',c.time||'—');text('gauge-clock-date',c.date||'—');}
async function diagnostics(){const r=await call('diagnostics');if(r.ok)Object.entries(r.diagnostics).forEach(([k,v])=>text('val-'+k,v));}
async function enter(){ready=true;show('auth-modal',false);setState('idle');sound('wake');await telemetry();}
async function authenticate(){const enrollment=!enrolled;const input=$(enrollment?'enroll-passphrase':'auth-passphrase');const data={passphrase:input.value};if(enrollment)data.confirm=$('enroll-confirm').value;$('btn-submit-auth').disabled=true;const r=await call('authenticate',data);input.value='';$('enroll-confirm').value='';delete data.passphrase;delete data.confirm;$('btn-submit-auth').disabled=false;if(r.ok)await enter();}
async function send(){const input=$('chat-text-input'),value=input.value.trim();if(!value||busy||state==='sleeping')return;const r=await call('chat',{text:value});if(r.ok){message(value,'user');input.value='';busy=true;setState('thinking');}}
async function startPTT(){if(ptt||busy||senses.open_mic||!ready)return;ptt=true;const r=await call('record_start');if(!r.ok)ptt=false;}
async function stopPTT(){if(!ptt)return;ptt=false;await call('record_stop');}
async function sense(name,enabled){const r=await call('sense',{name,enabled});if(r.ok)senses=r.senses;senseDisplay();}
async function loadRecords(kind){const r=await call(kind);if(!r.ok)return;if(kind==='memories'){records=r.records;renderMemories();}else renderRows('events-list',r.records);}
function renderRows(id,items){const box=$(id);box.replaceChildren();if(!items.length){const n=document.createElement('p');n.textContent='No records yet.';box.append(n);}for(const item of items){const row=document.createElement('div');row.className='memory-row';row.textContent=typeof item==='string'?item:Object.entries(item).map(([k,v])=>`${k}: ${v}`).join('\n');box.append(row);}}
function renderMemories(){const q=$('memory-search-input').value.toLowerCase();renderRows('memory-list',records.filter(r=>JSON.stringify(r).toLowerCase().includes(q)));}
document.querySelectorAll('.nav-item').forEach(button=>button.onclick=()=>{visibleTab=button.dataset.tab;document.querySelectorAll('.nav-item,.tab-pane').forEach(e=>e.classList.remove('active'));button.classList.add('active');$(visibleTab).classList.add('active');if(visibleTab==='tab-mind')loadRecords('memories');});
document.querySelectorAll('.subtab-btn').forEach(button=>button.onclick=()=>{document.querySelectorAll('.subtab-btn,.subtab-content').forEach(e=>e.classList.remove('active'));button.classList.add('active');$(button.dataset.subtab).classList.add('active');if(button.dataset.subtab==='subtab-events')loadRecords('events');if(button.dataset.subtab==='subtab-psc')loadRecords('memories');});
$('btn-send-text').onclick=send;$('chat-text-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send();}};
$('btn-ptt').onpointerdown=e=>{e.preventDefault();$('btn-ptt').setPointerCapture(e.pointerId);startPTT();};$('btn-ptt').onpointerup=stopPTT;$('btn-ptt').onpointercancel=stopPTT;
const keyName=e=>e.code==='Space'?'Space':e.key;
document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||!ready)return;if(keyName(e)===hotkey){e.preventDefault();startPTT();}});
document.addEventListener('keyup',e=>{if(keyName(e)===hotkey)stopPTT();});window.addEventListener('blur',stopPTT);
$('toggle-camera').onchange=e=>sense('camera',e.target.checked);$('toggle-voice').onchange=e=>sense('mic',e.target.checked);$('btn-toggle-voice-mode').onclick=()=>sense('open_mic',!senses.open_mic);
$('btn-trigger-sleep').onclick=()=>call('sleep');$('btn-trigger-wake').onclick=()=>call('wake');$('btn-quick-sleep').onclick=()=>call(state==='sleeping'?'wake':'sleep');
$('btn-refresh-memories').onclick=()=>loadRecords('memories');$('btn-refresh-events').onclick=()=>loadRecords('events');$('memory-search-input').oninput=renderMemories;
$('setting-hotkey').onchange=async e=>{const r=await call('settings',{hotkey:e.target.value});if(r.ok){hotkey=r.settings.hotkey;text('ptt-hotkey-badge','['+hotkey.toUpperCase()+']');}};
$('setting-audio-chimes').onchange=async e=>{const r=await call('settings',{chimes:e.target.checked});if(r.ok)chimes=r.settings.chimes;};$('setting-close-to-tray').onchange=e=>call('settings',{close_to_tray:e.target.checked});
$('btn-minimize').onclick=()=>call('window',{action:'minimize'});$('btn-minimize-tray').onclick=()=>call('window',{action:'hide'});$('btn-close').onclick=()=>call('window',{action:'close'});
$('btn-submit-auth').onclick=authenticate;for(const id of ['auth-passphrase','enroll-confirm'])$(id).onkeydown=e=>{if(e.key==='Enter')authenticate();};
$('btn-proceed-unauth').onclick=async()=>{const r=await call('continue');if(r.ok)await enter();};$('diag-toggle').onclick=()=>show('diag-body',$('diag-body').style.display==='none');$('btn-recheck-env').onclick=diagnostics;
window.addEventListener('pywebviewready',async()=>{const r=await call('boot');if(!r.ok){text('splash-status-text',r.error||'Unable to start the local mind.');return;}enrolled=r.enrolled;hotkey=r.settings.hotkey;chimes=r.settings.chimes;$('setting-hotkey').value=hotkey;$('setting-audio-chimes').checked=chimes;$('setting-close-to-tray').checked=r.settings.close_to_tray;text('ptt-hotkey-badge','['+hotkey.toUpperCase()+']');text('fence-indicator','● FENCE ACTIVE');text('mode-indicator',r.backend==='llm'?'LOCAL LLM':'LOCAL RULE ENGINE');text('auth-modal-title',enrolled?'WELCOME BACK':'WELCOME TO JARVIS');text('auth-modal-subtitle',enrolled?'Enter your passphrase to verify this session.':'Create a passphrase of at least 12 characters. Your senses remain off until you enable them.');show('enrollment-fields',!enrolled);show('auth-fields',enrolled);show('diag-body');show('boot-splash',false);show('auth-modal');text('btn-submit-auth',enrolled?'Unlock Session':'Create Passphrase');diagnostics();setInterval(poll,180);});
// A procedural eye, drawn locally. State derives exclusively from backend events.
const canvas=$('eye-canvas'),ctx=canvas.getContext('2d'),wave=$('waveform-canvas'),wc=wave.getContext('2d');
function draw(t){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const time=reduced?0:t/1000;ctx.clearRect(0,0,160,160);const asleep=state==='sleeping',talk=state==='speaking',thinking=state==='thinking'||state==='consolidating';const color=asleep?'217,127,65':'85,225,207';const pulse=asleep?1:1+Math.sin(time*(thinking?5:1.8))*.1;const radius=(asleep?9:17)*pulse;const glow=ctx.createRadialGradient(80,80,0,80,80,70);glow.addColorStop(0,`rgba(${color},${asleep?.3:.45})`);glow.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=glow;ctx.fillRect(0,0,160,160);for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(80,80,34+i*15+(talk?Math.sin(time*5-i)*5:0),time*(i%2?-.15:.15),time*(i%2?-.15:.15)+Math.PI*(thinking?1.5:1.88));ctx.strokeStyle=`rgba(${color},${asleep?.13:.22-i*.035})`;ctx.lineWidth=1;ctx.stroke();}ctx.beginPath();ctx.arc(80,80,radius,0,Math.PI*2);ctx.fillStyle=`rgba(${color},${asleep?.45:.85})`;ctx.shadowBlur=20;ctx.shadowColor=`rgb(${color})`;ctx.fill();ctx.shadowBlur=0;wc.clearRect(0,0,280,36);wc.beginPath();for(let x=0;x<280;x++){const y=18+Math.sin(x*.16-time*15)*Math.sin(x*.033)*Math.min(16,level*240);x?wc.lineTo(x,y):wc.moveTo(x,y);}wc.strokeStyle='#78e7cc';wc.stroke();requestAnimationFrame(draw);}requestAnimationFrame(draw);
